// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Driver struct {
	ID         int32          `json:"id"`
	LineID     string         `json:"line_id"`
	DriverName string         `json:"driver_name"`
	CarNo      string         `json:"car_no"`
	CarBrand   string         `json:"car_brand"`
	CarModel   string         `json:"car_model"`
	CarColor   string         `json:"car_color"`
	Phone      sql.NullString `json:"phone"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type RideOrder struct {
	ID          int32          `json:"id"`
	StoreID     int32          `json:"store_id"`
	RiderName   sql.NullString `json:"rider_name"`
	DriverID    int32          `json:"driver_id"`
	AddressTo   sql.NullString `json:"address_to"`
	AskInTime   time.Time      `json:"ask_in_time"`
	PickUpTime  sql.NullTime   `json:"pick_up_time"`
	GetOutTime  sql.NullTime   `json:"get_out_time"`
	Status      sql.NullInt32  `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	OrderType   sql.NullInt32  `json:"order_type"`
	ChallengeAt sql.NullTime   `json:"challenge_at"`
}

type Store struct {
	ID        int32        `json:"id"`
	LineID    string       `json:"line_id"`
	StoreName string       `json:"store_name"`
	Address   string       `json:"address"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type StoreBalance struct {
	ID        int32        `json:"id"`
	StoreID   int32        `json:"store_id"`
	Amount    int32        `json:"amount"`
	TypeID    string       `json:"type_id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
